%% Clear Workspace
clear; clc; close all;

%% Define the available years (adjust as needed)
start_year = 2009;
end_year   = 2017;

%% Load the Lorenzo sample status dataset (firms that are contained in Lorenzo's sample)
% This file (lorenzo_sample.csv) contains two columns:
%   - identificad: Unique employer ID (as in all your datasets)
%   - lorenzo_sample: Dummy variable (1 if the employer belongs to lorenzo's sample, 0 otherwise)
lorenzoData = readtable("/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/lorenzo_sample.csv");
% Convert the employer IDs to strings for consistent matching
lorenzoData.identificad = string(lorenzoData.identificad);

%% Initialize a cell array to store connectivity tables for each pair
connTables = {};

%% Nested loop: For each starting year y and every later year nextYear
for y = start_year:(end_year - 1)
    nextYear = (y+1);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Read the merged data for the year pair.
        % Use sprintf to build the file name string.
        % (This file should already be generated by your Stata code.)
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        filename = sprintf('/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/employers_full_%d_%d.csv', y, nextYear);
        mergedData = readtable(filename);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Extract employer IDs from the merged data.
        % We assume that the variables are named "identificad_y" and "identificad_nextYear"
        % (e.g., "identificad_2009" and "identificad_2010").
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        emp_y = string(mergedData.(['identificad_' num2str(y)]));
        emp_next = string(mergedData.(['identificad_' num2str(nextYear)]));
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Build a unique employer mapping from the merged data.
        % This gives all unique employer IDs from both years.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        unique_emps = unique([emp_y; emp_next]);
        nEmps = length(unique_emps);
        
        % Map each employer ID to its index in unique_emps.
        [~, emp_y_idx] = ismember(emp_y, unique_emps);
        [~, emp_next_idx] = ismember(emp_next, unique_emps);
        
        % Remove any rows where indices are invalid (i.e., zero)
        valid_idx = (emp_y_idx > 0) & (emp_next_idx > 0);
        emp_y_idx = emp_y_idx(valid_idx);
        emp_next_idx = emp_next_idx(valid_idx);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Construct the adjacency (connectivity) matrix.
        % M(i,j) counts the number of worker flows from employer i (year y)
        % to employer j (year nextYear).
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        M = sparse(emp_y_idx, emp_next_idx, 1, nEmps, nEmps);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Assign treatment status for each unique employer.
        % For each employer in unique_emps, match it to treatData.
        % isTreated is a numeric vector where 1 = treated and 0 = untreated.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        [~, sample_idx] = ismember(unique_emps, lorenzoData.identificad);
        isSample = zeros(nEmps, 1);
        isSample(sample_idx > 0) = lorenzoData.lorenzo_sample(sample_idx(sample_idx > 0));
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Compute raw flow measures:
        % - totalOut: total workers leaving (row sum of M)
        % - totalIn: total workers arriving (column sum of M)
        % - totalFlows: sum of outflow and inflow for each employer
        % - outToTreated: outflow from employer (row sum) but only to treated firms
        % - inFromTreated: inflow into employer (column sum) but only from treated firms
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        totalOut = full(sum(M, 2));
        totalIn = full(sum(M, 1))';
        totalFlows = totalOut + totalIn;
        
        outToSample = full(sum(M(:, isSample == 1), 2));
        inFromSample = full(sum(M(isSample == 1, :), 1))';
        sampleFlows = outToSample + inFromSample;
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Compute connectivity percentage, infromtreat percentage and outtotreat percent:
        % This is 100 * (treatedFlows / totalFlows)
        % infromt_p = 100* (outToTreated/totalOut)
        % outfot_ = 100*(inFromTreated/totalIn)
        % Employers with zero total flows are assigned NaN.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        connectivityPercentage = 100 * (sampleFlows ./ totalFlows);
        connectivityPercentage(totalFlows == 0) = NaN;
        
        outtosample_p = 100 * (outToSample ./ totalOut);
        outtosample_p(totalOut==0) = NaN;
        
        infromsample_p = 100 * (inFromSample ./ totalIn);
        infromsample_p(totalIn==0) = NaN;

        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Create a table for this year pair.
        % The employer identifier is always named "identificad".
        % Other columns are the connectivity percentage, raw outflow, and raw inflow.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        T_pair = table(unique_emps, connectivityPercentage, outToSample, inFromSample, outtosample_p, infromsample_p, ...
            'VariableNames', {'identificad', 'Connectivity_Percentage', 'OutflowSample', 'InflowSample', 'outtosample_p','infromsample_p'});
        
        % Rename the connectivity variables to include the year pair information.
        connVarName = sprintf('con_sample_%d_%d', y, nextYear);
        outVarName  = sprintf('outs_%d_%d', y, nextYear);
        outtpVarName = sprintf('outtosample_p_%d_%d',y,nextYear);
        inVarName   = sprintf('ins_%d_%d', y, nextYear);
        inftpVarName = sprintf('infromsample_p_%d_%d', y, nextYear);
        
        T_pair.Properties.VariableNames{'Connectivity_Percentage'} = connVarName;
        T_pair.Properties.VariableNames{'OutflowSample'} = outVarName;
        T_pair.Properties.VariableNames{'InflowSample'} = inVarName;
        T_pair.Properties.VariableNames{'outtosample_p'} = outtpVarName;
        T_pair.Properties.VariableNames{'infromsample_p'} = inftpVarName;
        
        % Store this table in our cell array.
        connTables{end+1} = T_pair;
        
        fprintf('Processed connectivity measures with lorenzo sample for year pair %d-%d.\n', y, nextYear);
end

%% Merge All Connectivity Tables into One Final Table
% Use an outer join on "identificad" so that every employer is included.
finalTable = connTables{1};
for k = 2:length(connTables)
    finalTable = outerjoin(finalTable, connTables{k}, 'MergeKeys', true, 'Type', 'full');
end

% (Optional) Sort the final table by identificad.
finalTable = sortrows(finalTable, 'identificad');

%% Merge the Treatment Dataset with the Final Connectivity Table
% This adds the treatment dummy (treat_ultra) to the final table.
mergedTable = outerjoin(finalTable, lorenzoData, 'MergeKeys', true, 'Type', 'full');
% Assume missing treatment status equals 0.
missingSample = isnan(mergedTable.lorenzo_sample);
mergedTable.lorenzo_sample(missingSample) = 0;

%% Save the Final Merged Connectivity Dataset
outputFile = '/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/connectivity_lsample_2009_2017.csv';
writetable(mergedTable, outputFile);

disp('Final merged connectivity with lorenzo sample dataset (for all pairs) with treatment dummy has been saved as connectivity_lsample_2009_2017.csv.');