#!/usr/bin/env python3
"""
Figure 3 (corrected covariate adjustment) — Cattaneo et al. (2024) Problem 1 fix.

Instead of pre-residualizing x and y before binsreg (which is only valid under
linearity), this script passes raw variables to binsreg with the control matrix w
passed directly, letting binsreg implement the semi-linear partial-mean estimator
(equation 3/6 in Cattaneo et al. 2024).

After firm-level DiD differencing, the industry×year, mode×year, microregion×year
FEs collapse to group dummies, and the three baseline-quartile×year sets collapse
to baseline-quartile dummies. These are passed as w.

Requires: Tables/conn_margins/scatter_raw_controls.csv
  (generated by conn_margins_scatter_controls.do)

Output: Graphs/conn_margins/linearity_fig3_binsreg_corrected.pdf
"""

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import statsmodels.api as sm
import binsreg
from pathlib import Path

FONT_PATH = "/kellogg/proj/lgg3230/UnionSpill/fonts/LibertinusSerif-Regular.otf"
BLUE = "#2166AC"
RED  = "#B2182B"

script_dir = Path(__file__).resolve().parent
tables_dir = script_dir.parent.parent / "Tables" / "conn_margins"
graphs_dir = script_dir.parent.parent / "Graphs" / "conn_margins"
graphs_dir.mkdir(parents=True, exist_ok=True)

if Path(FONT_PATH).exists():
    fm.fontManager.addfont(FONT_PATH)
    plt.rcParams["font.family"] = "Libertinus Serif"

# ── Load raw firm-level data + controls ───────────────────────────────────────

df = pd.read_csv(tables_dir / "scatter_raw_controls.csv")
df = df.dropna(subset=["conn_firm", "raw_did"])
print(f"Firms: {len(df):,}")

x = df["conn_firm"].values.astype(float)
y = df["raw_did"].values.astype(float)

x_lo = np.quantile(x, 0.01)
x_hi = np.quantile(x, 0.99)

# ── Build control matrix w ────────────────────────────────────────────────────
# After DiD differencing, ×year FEs collapse to group dummies.
# Dummify all categorical controls; drop one level each to avoid multicollinearity.

cat_cols = ["industry1", "mode_base_month", "microregion",
            "lr_remdezr_w_pre4", "l_firm_emp_pre4", "totalflows_pw_pre_07_114"]

for col in cat_cols:
    df[col] = df[col].astype("category")

W = pd.get_dummies(df[cat_cols], drop_first=True, dtype=float)
print(f"Control matrix shape: {W.shape}  ({W.shape[1]} dummies)")

# ── binsreg: correct covariate adjustment (50 bins, uniform CB) ───────────────

np.random.seed(42)
x_jitter = x + np.random.uniform(0, 1e-8, len(x))
df_bs = pd.DataFrame({"y": y, "x": x_jitter})
df_bs = pd.concat([df_bs, W.reset_index(drop=True)], axis=1)

w_cols = W.columns.tolist()

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    res = binsreg.binsreg("y", "x", w=w_cols, data=df_bs,
                          noplot=True, nbins=50, cb=(3, 3))
    tst = binsreg.binstest("y", "x", w=w_cols, data=df_bs,
                           testmodelpoly=1, nsims=2000, simsseed=42, simsgrid=50)

d    = res.data_plot[0]
dots = d.dots
cb   = d.cb
print(f"Bins: {len(dots)}")

p_val = float(tst.testpoly.pval[0])
t_stat = float(tst.testpoly.stat[0])
print(f"Linearity test — stat: {t_stat:.4f}, p-value: {p_val:.4f}")

# ── OLS with same controls ────────────────────────────────────────────────────

x_grid = np.linspace(x_lo, x_hi, 300)
Xmat   = sm.add_constant(np.column_stack([x] + [W[c].values for c in w_cols]))
mod    = sm.OLS(y, Xmat).fit()
slope  = mod.params[1]
print(f"OLS slope on conn_firm (controlling for w): {slope:.4f}")

# Predict on grid holding w at mean
w_means = W.mean().values
Xg = np.column_stack([np.ones(300), x_grid] +
                     [np.full(300, w_means[i]) for i in range(len(w_cols))])
pr     = mod.get_prediction(Xg)
ols_ci = pr.conf_int()

# ── Plot ─────────────────────────────────────────────────────────────────────

fig, ax = plt.subplots(figsize=(7, 4.8))

ax.fill_between(cb["x"], cb["cb_l"], cb["cb_r"],
                color=BLUE, alpha=0.15, zorder=2,
                label="95% uniform confidence band (50 bins)")
ax.scatter(dots["x"], dots["fit"],
           s=20, color=BLUE, zorder=4, linewidths=0,
           label="Bin means")

ax.fill_between(x_grid, ols_ci[:, 0], ols_ci[:, 1],
                color=RED, alpha=0.12, zorder=1)
ax.plot(x_grid, pr.predicted_mean, color=RED, linewidth=1.8, zorder=5,
        label=f"OLS + 95% CI  (slope: {slope:.4f})")

ax.axhline(0, color="gray", linewidth=0.5, linestyle="--", alpha=0.4)
ax.axvline(0, color="gray", linewidth=0.5, linestyle="--", alpha=0.4)
ax.set_xlim(-0.15, 2.5)
ax.set_ylim(0, 0.25)

p_str = f"$p = {p_val:.3f}$" if p_val >= 0.001 else "$p < 0.001$"
ax.text(0.98, 0.97, f"Linearity test: {p_str}",
        transform=ax.transAxes, ha="right", va="top",
        fontsize=9, style="italic")

ax.set_xlabel("Connectivity to treated firms (normalized)", fontsize=11)
ax.set_ylabel("Post \u2212 Pre log wages (raw DiD)", fontsize=11)
ax.tick_params(labelsize=10)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.legend(frameon=False, fontsize=9.5,
          loc="upper center", bbox_to_anchor=(0.5, -0.18), ncol=2)

fig.tight_layout(rect=[0, 0.06, 1, 1])

out = graphs_dir / "linearity_fig3_binsreg_corrected.pdf"
fig.savefig(out, bbox_inches="tight")
print(f"Saved: {out}")
