/*
================================================================================
linearity_polytest.do — Parametric quadratic/cubic augmentation F-test
                         for the continuous-connectivity spillover DiD

Complements the nonparametric binsreg tests (linearity_did_fd.do,
linearity_binstest.do) and the binned event study (linearity_did.do Part B)
with the parametric check the linearity playbook recommends but never coded
(see linearity_defense.md, "Formal(ish) tests", lines 149-153):

  Add conn^2 and conn^3 to the baseline spillover DiD and jointly test
        H0:  higher-order post-reform coefficients = 0.
  Non-rejection => the linear-in-connectivity restriction is adequate.

Reported in the same fashion as the MAIN SPILLOVER TABLE (tab:spill_base,
generated by _spill_base_only.do / Main_Results_pct_tfpw_07_11.do Part D):
  - Full spillover sample s_spill (NOT intensive-margin), continuous conn.
  - Post x Connectivity (treat_year, 2012-2016 effect)  + quad + cube
  - Pre  x Connectivity (placebo_year, 2009-2010 vs 2011) + quad + cube
  - Joint F-tests of the higher-order terms (post = linearity test;
    pre = placebo / pre-trend curvature test)

Baseline spec being defended (_spill_base_only.do):
    reghdfe Y c.totaltreat_pw_norm##i.treat_year if `s_spill',
        absorb(base_fe + Y_pre4#year + l_firm_emp_pre4#year + extra_year)
        vce(cluster identificad)

Augmented spec (post):
    reghdfe Y c.conn##i.treat_year c.conn2##i.treat_year c.conn3##i.treat_year
        if `s_spill', absorb(<same>) vce(cluster identificad)
    test 1.treat_year#c.conn2 1.treat_year#c.conn3

Outcomes: log wages, log hourly wages, log employment (calendar-year), and the
          number of CBA clauses (CBA negotiation-period structure).

Output (Tables/conn_margins/):
  linearity_polytest.csv  — long format: outcome, term, b, se, p (post & pre),
                            plus joint F / p (post & pre), n_obs, n_estab.
================================================================================
*/

version 17.0
set more off
set varabbrev off

* ── Paths (auto-detect cluster vs. local Mac) ─────────────────────────────────

capture confirm file "/kellogg/proj/lgg3230/UnionSpill/Data"
if _rc == 0 {
	global main "/kellogg/proj/lgg3230/UnionSpill"
	local on_cluster = 1
}
else {
	* Mac: this file lives in <repo>/Cluster/UnionSpill/Programs/conn_margins/
	global main "/Users/luisg/Library/CloudStorage/OneDrive-NorthwesternUniversity/4 - PhD/02_Research/Org_Econ BR/UnionSpillovers/Cluster/UnionSpill"
	local on_cluster = 0
}

global rais_firm "$main/Data/CBA_RAIS_firm_level"
global rais_aux  "$main/Data/RAIS_aux"
global tables    "$main/Tables"
global logs      "$main/Logs"

cap mkdir "$tables"
cap mkdir "$tables/conn_margins"
cap mkdir "$logs"
cap mkdir "$logs/conn_margins"

capture log close
local d = subinstr("`c(current_date)'"," ","_",.)
local t = subinstr("`c(current_time)'",":","",.)
log using "$logs/conn_margins/linearity_polytest_`d'_`t'.log", replace text

di "Started: `c(current_date)' `c(current_time)'   on_cluster=`on_cluster'"

* ── Load data ─────────────────────────────────────────────────────────────────

use "$rais_firm/lagos_sample_sep24_pct_unionexp_ext_df2.dta", clear

* ── Merge totalflows ─────────────────────────────────────────────────────────

preserve
	import delimited "$rais_aux/totalflows_wide_2007_2011.csv", clear
	tostring identificad, replace format(%014.0f) force
	tempfile totalflows_wide
	save `totalflows_wide'
restore

merge m:1 identificad using `totalflows_wide', keep(master match) nogen

gen double totalflows_pw_pre_07_11 = 0
gen totalflows_pw_pre_07_11_cnt = 0
foreach yp in totalflows_pw_07_08 totalflows_pw_08_09 totalflows_pw_09_10 totalflows_pw_10_11 {
	replace totalflows_pw_pre_07_11 = totalflows_pw_pre_07_11 + `yp' if !missing(`yp')
	replace totalflows_pw_pre_07_11_cnt = totalflows_pw_pre_07_11_cnt + (!missing(`yp'))
}
replace totalflows_pw_pre_07_11 = totalflows_pw_pre_07_11 / totalflows_pw_pre_07_11_cnt ///
	if totalflows_pw_pre_07_11_cnt > 0
replace totalflows_pw_pre_07_11 = . if totalflows_pw_pre_07_11_cnt == 0
drop totalflows_pw_pre_07_11_cnt

keep if year >= 2009
keep if lagos_sample_avg == 1

* ── Sample + treatment indicators (mirror _spill_base_only.do) ────────────────

local s_spill "lagos_sample_avg==1 & treat_ultra==0 & in_balanced_panel==1"

cap drop placebo_year
gen byte placebo_year = (year < 2011)

cap drop treat_year
gen byte treat_year = (year >= 2012)

* CBA negotiation-period indicators (for numb_clauses)
cap drop cba_period
gen cba_period = .
replace cba_period = 1 if avg_file_date == earliest2009_avg - 1 & !missing(avg_file_date)
replace cba_period = 2 if avg_file_date == second_cba_avg        & !missing(avg_file_date)
replace cba_period = 3 if inrange(avg_file_date, mdy(1,1,2013), mdy(12,31,2013)) & cba_period == .
replace cba_period = 4 if inrange(avg_file_date, mdy(1,1,2014), mdy(12,31,2014)) & cba_period == .
replace cba_period = 5 if inrange(avg_file_date, mdy(1,1,2015), mdy(12,31,2015)) & cba_period == .
replace cba_period = 6 if inrange(avg_file_date, mdy(1,1,2016), mdy(12,31,2016)) & cba_period == .

cap drop pre_treat_cba
gen byte pre_treat_cba  = cond(cba_period <  2, 1, 0)
cap drop post_treat_cba
gen byte post_treat_cba = cond(cba_period >= 3, 1, 0) if !missing(cba_period)

* ── Connectivity scaling (p90 among full spillover sample in 2009) ────────────

cap drop totaltreat_pw_n_p90
cap drop totaltreat_pw_norm
sum totaltreat_pw_n if `s_spill' & year == 2009, detail
gen double totaltreat_pw_n_p90 = r(p90)
gen double totaltreat_pw_norm  = totaltreat_pw_n / totaltreat_pw_n_p90

* Higher-order connectivity terms
cap drop conn2
cap drop conn3
gen double conn2 = totaltreat_pw_norm^2
gen double conn3 = totaltreat_pw_norm^3

* ── Pre-treatment controls (mirror _spill_base_only.do) ───────────────────────

cap drop firm_emp_pre_o
cap drop firm_emp_pre
quietly {
	bys identificad: egen firm_emp_pre_o = mean(firm_emp) if inrange(year, 2009, 2011)
	bys identificad: egen firm_emp_pre   = min(firm_emp_pre_o)
	drop firm_emp_pre_o
}
cap drop l_firm_emp_pre
gen double l_firm_emp_pre = ln(firm_emp_pre)

cap drop l_firm_emp_pre4_o
cap drop l_firm_emp_pre4
quietly {
	egen l_firm_emp_pre4_o = cut(l_firm_emp_pre) if year == 2009 & in_balanced_panel == 1, group(4)
	bys identificad: egen l_firm_emp_pre4 = min(l_firm_emp_pre4_o)
	drop l_firm_emp_pre4_o
	replace l_firm_emp_pre4 = 0 if missing(l_firm_emp_pre4)
}

cap drop totalflows_pw_pre_07_114_o
cap drop totalflows_pw_pre_07_114
quietly {
	egen totalflows_pw_pre_07_114_o = cut(totalflows_pw_pre_07_11) ///
		if year == 2009 & in_balanced_panel == 1, group(4)
	bys identificad: egen totalflows_pw_pre_07_114 = min(totalflows_pw_pre_07_114_o)
	drop totalflows_pw_pre_07_114_o
	replace totalflows_pw_pre_07_114 = 0 if missing(totalflows_pw_pre_07_114)
}

* Per-outcome pre-treatment mean + 4-bin control (calendar outcomes)
foreach outcome in lr_remdezr_w lr_remdezr_h_w l_firm_emp {
	cap drop `outcome'_pre_o
	cap drop `outcome'_pre
	cap drop `outcome'_pre4_o
	cap drop `outcome'_pre4
	quietly {
		bys identificad: egen `outcome'_pre_o = mean(`outcome') if inrange(year, 2009, 2011)
		bys identificad: egen `outcome'_pre   = min(`outcome'_pre_o)
		drop `outcome'_pre_o
		egen `outcome'_pre4_o = cut(`outcome'_pre) if year == 2009 & in_balanced_panel == 1, group(4)
		bys identificad: egen `outcome'_pre4 = min(`outcome'_pre4_o)
		drop `outcome'_pre4_o
		replace `outcome'_pre4 = 0 if missing(`outcome'_pre4)
	}
}

* numb_clauses pre-treatment mean (CBA periods 1-2) + 4-bin control
capture confirm variable numb_clauses
if _rc == 0 {
	cap drop numb_clauses_pre_o
	cap drop numb_clauses_pre
	quietly {
		bys identificad: egen numb_clauses_pre_o = mean(numb_clauses) if inrange(cba_period, 1, 2)
		bys identificad: egen numb_clauses_pre   = min(numb_clauses_pre_o)
		drop numb_clauses_pre_o
	}
	cap drop numb_clauses_pre4_o
	cap drop numb_clauses_pre4
	quietly {
		egen numb_clauses_pre4_o = cut(numb_clauses_pre) if year == 2009 & in_balanced_panel == 1, group(4)
		bys identificad: egen numb_clauses_pre4 = min(numb_clauses_pre4_o)
		drop numb_clauses_pre4_o
		replace numb_clauses_pre4 = 0 if missing(numb_clauses_pre4)
	}
}

* ── FE macros (mirror _spill_base_only.do / conn_margins.do exactly) ──────────

local base_fe     "identificad i.industry1#i.year i.mode_base_month#i.year i.microregion#i.year"
local extra_year  "ib0.totalflows_pw_pre_07_114#i.year"
local base_fe_cba "identificad i.industry1#i.cba_period i.mode_base_month#i.cba_period i.microregion#i.cba_period"
local extra_cba   "ib0.totalflows_pw_pre_07_114#i.cba_period"

local conn "totaltreat_pw_norm"

* ── Output CSV (long format) ──────────────────────────────────────────────────

tempname fp
file open `fp' using "$tables/conn_margins/linearity_polytest.csv", write replace
file write `fp' "outcome,term,post_b,post_se,post_p,pre_b,pre_se,pre_p,F_post,p_post,F_pre,p_pre,n_obs,n_estab" _n

********************************************************************************
* CALENDAR-YEAR OUTCOMES (log wages, log hourly wages, log employment)
********************************************************************************

foreach outcome in lr_remdezr_w lr_remdezr_h_w l_firm_emp {

	di _newline "============================================================"
	di "Poly augmentation (full spillover sample): `outcome'"
	di "============================================================"

	local absorb "`base_fe' ib0.`outcome'_pre4#i.year ib0.l_firm_emp_pre4#i.year `extra_year'"

	* ── POST: augmented spec on full sample ──────────────────────────────────
	reghdfe `outcome' c.`conn'##i.treat_year c.conn2##i.treat_year c.conn3##i.treat_year ///
		if `s_spill', absorb(`absorb') vce(cluster identificad)

	local n_obs   = e(N)
	local n_estab = e(N_clust)
	local dfr     = e(df_r)

	local post_b_lin  = _b[1.treat_year#c.`conn']
	local post_se_lin = _se[1.treat_year#c.`conn']
	local post_p_lin  = 2*ttail(`dfr', abs(`post_b_lin'/`post_se_lin'))
	local post_b_qua  = _b[1.treat_year#c.conn2]
	local post_se_qua = _se[1.treat_year#c.conn2]
	local post_p_qua  = 2*ttail(`dfr', abs(`post_b_qua'/`post_se_qua'))
	local post_b_cub  = _b[1.treat_year#c.conn3]
	local post_se_cub = _se[1.treat_year#c.conn3]
	local post_p_cub  = 2*ttail(`dfr', abs(`post_b_cub'/`post_se_cub'))

	test 1.treat_year#c.conn2 1.treat_year#c.conn3
	local F_post = r(F)
	local p_post = r(p)

	* ── PRE placebo: augmented spec, 2009-2010 vs 2011 ───────────────────────
	reghdfe `outcome' c.`conn'##i.placebo_year c.conn2##i.placebo_year c.conn3##i.placebo_year ///
		if `s_spill' & year <= 2011, absorb(`absorb') vce(cluster identificad)

	local dfrp = e(df_r)

	local pre_b_lin  = _b[1.placebo_year#c.`conn']
	local pre_se_lin = _se[1.placebo_year#c.`conn']
	local pre_p_lin  = 2*ttail(`dfrp', abs(`pre_b_lin'/`pre_se_lin'))
	local pre_b_qua  = _b[1.placebo_year#c.conn2]
	local pre_se_qua = _se[1.placebo_year#c.conn2]
	local pre_p_qua  = 2*ttail(`dfrp', abs(`pre_b_qua'/`pre_se_qua'))
	local pre_b_cub  = _b[1.placebo_year#c.conn3]
	local pre_se_cub = _se[1.placebo_year#c.conn3]
	local pre_p_cub  = 2*ttail(`dfrp', abs(`pre_b_cub'/`pre_se_cub'))

	test 1.placebo_year#c.conn2 1.placebo_year#c.conn3
	local F_pre = r(F)
	local p_pre = r(p)

	* ── Report + write (one row per term; F/p and N repeated on lin row) ─────
	di as result "  POST  lin=" %8.4f `post_b_lin' "  quad=" %8.4f `post_b_qua' "  cube=" %8.4f `post_b_cub'
	di as result "  PRE   lin=" %8.4f `pre_b_lin'  "  quad=" %8.4f `pre_b_qua'  "  cube=" %8.4f `pre_b_cub'
	di as result "  Joint F(2,`=`dfr'') post=" %7.4f `F_post' " p=" %6.4f `p_post' ///
	             "   pre=" %7.4f `F_pre' " p=" %6.4f `p_pre'
	di as result "  N=`n_obs'  estab=`n_estab'"

	file write `fp' "`outcome',lin,`post_b_lin',`post_se_lin',`post_p_lin',`pre_b_lin',`pre_se_lin',`pre_p_lin',`F_post',`p_post',`F_pre',`p_pre',`n_obs',`n_estab'" _n
	file write `fp' "`outcome',quad,`post_b_qua',`post_se_qua',`post_p_qua',`pre_b_qua',`pre_se_qua',`pre_p_qua',,,,,," _n
	file write `fp' "`outcome',cube,`post_b_cub',`post_se_cub',`post_p_cub',`pre_b_cub',`pre_se_cub',`pre_p_cub',,,,,," _n
}

********************************************************************************
* numb_clauses (CBA-period structure, full spillover sample)
********************************************************************************

capture confirm variable numb_clauses
if _rc == 0 {

	di _newline "============================================================"
	di "Poly augmentation (full spillover sample): numb_clauses (CBA periods)"
	di "============================================================"

	local absorb_cba "`base_fe_cba' ib0.numb_clauses_pre4#i.cba_period ib0.l_firm_emp_pre4#i.cba_period `extra_cba'"

	* ── POST ─────────────────────────────────────────────────────────────────
	reghdfe numb_clauses c.`conn'##post_treat_cba c.conn2##post_treat_cba c.conn3##post_treat_cba ///
		if `s_spill' & !missing(cba_period), absorb(`absorb_cba') vce(cluster identificad)

	local n_obs   = e(N)
	local n_estab = e(N_clust)
	local dfr     = e(df_r)

	local post_b_lin  = _b[1.post_treat_cba#c.`conn']
	local post_se_lin = _se[1.post_treat_cba#c.`conn']
	local post_p_lin  = 2*ttail(`dfr', abs(`post_b_lin'/`post_se_lin'))
	local post_b_qua  = _b[1.post_treat_cba#c.conn2]
	local post_se_qua = _se[1.post_treat_cba#c.conn2]
	local post_p_qua  = 2*ttail(`dfr', abs(`post_b_qua'/`post_se_qua'))
	local post_b_cub  = _b[1.post_treat_cba#c.conn3]
	local post_se_cub = _se[1.post_treat_cba#c.conn3]
	local post_p_cub  = 2*ttail(`dfr', abs(`post_b_cub'/`post_se_cub'))

	test 1.post_treat_cba#c.conn2 1.post_treat_cba#c.conn3
	local F_post = r(F)
	local p_post = r(p)

	* ── PRE placebo (CBA periods 1-2; base period 2) ─────────────────────────
	reghdfe numb_clauses c.`conn'##pre_treat_cba c.conn2##pre_treat_cba c.conn3##pre_treat_cba ///
		if `s_spill' & !missing(cba_period) & cba_period <= 2, absorb(`absorb_cba') vce(cluster identificad)

	local dfrp = e(df_r)

	local pre_b_lin  = _b[1.pre_treat_cba#c.`conn']
	local pre_se_lin = _se[1.pre_treat_cba#c.`conn']
	local pre_p_lin  = 2*ttail(`dfrp', abs(`pre_b_lin'/`pre_se_lin'))
	local pre_b_qua  = _b[1.pre_treat_cba#c.conn2]
	local pre_se_qua = _se[1.pre_treat_cba#c.conn2]
	local pre_p_qua  = 2*ttail(`dfrp', abs(`pre_b_qua'/`pre_se_qua'))
	local pre_b_cub  = _b[1.pre_treat_cba#c.conn3]
	local pre_se_cub = _se[1.pre_treat_cba#c.conn3]
	local pre_p_cub  = 2*ttail(`dfrp', abs(`pre_b_cub'/`pre_se_cub'))

	test 1.pre_treat_cba#c.conn2 1.pre_treat_cba#c.conn3
	local F_pre = r(F)
	local p_pre = r(p)

	di as result "  POST  lin=" %8.4f `post_b_lin' "  quad=" %8.4f `post_b_qua' "  cube=" %8.4f `post_b_cub'
	di as result "  PRE   lin=" %8.4f `pre_b_lin'  "  quad=" %8.4f `pre_b_qua'  "  cube=" %8.4f `pre_b_cub'
	di as result "  Joint F post=" %7.4f `F_post' " p=" %6.4f `p_post' ///
	             "   pre=" %7.4f `F_pre' " p=" %6.4f `p_pre'
	di as result "  N=`n_obs'  estab=`n_estab'"

	file write `fp' "numb_clauses,lin,`post_b_lin',`post_se_lin',`post_p_lin',`pre_b_lin',`pre_se_lin',`pre_p_lin',`F_post',`p_post',`F_pre',`p_pre',`n_obs',`n_estab'" _n
	file write `fp' "numb_clauses,quad,`post_b_qua',`post_se_qua',`post_p_qua',`pre_b_qua',`pre_se_qua',`pre_p_qua',,,,,," _n
	file write `fp' "numb_clauses,cube,`post_b_cub',`post_se_cub',`post_p_cub',`pre_b_cub',`pre_se_cub',`pre_p_cub',,,,,," _n
}

file close `fp'

* ── Summary ───────────────────────────────────────────────────────────────────

di _newline "======================================================="
di "LINEARITY POLY-AUGMENTATION (full spillover sample)"
di "See: $tables/conn_margins/linearity_polytest.csv"
di "======================================================="
type "$tables/conn_margins/linearity_polytest.csv"

capture log close

if `on_cluster' == 1 {
	shell source /gpfs/kellogg/proj/lgg3230/UnionSpill/Programs/notify.sh && ///
		notify "linearity_polytest done" "Quadratic/cubic augmentation F-test (full sample) complete"
}
