#!/usr/bin/env python3
"""Compile Tables A6, A7 and A8 (monthly and hourly) into one PDF.

The .tex fragments come from Luis's own 05b_make_tables_within_firm.py, run
unmodified over this package's CSVs, so the layout is identical by construction.

    python3 scripts/05b_make_tables_within_firm.py
    python3 scripts/build_pdf.py     ->  tables_A6_A7_A8.pdf
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "output"

TABLES = [
    ("t_layerdesc",     "Table A6 — Group-Level Connectivity Descriptives (monthly wages)"),
    ("t_groupspecs",    "Table A7 — Group-level spillover effects, revised specification (log monthly wages)"),
    ("t_horserace",     "Table A8 — Group-Specific Connectivity and Firm-Level Outcomes (log monthly wages)"),
    ("t_layerdesc_hw",  "Table A6 — Group-Level Connectivity Descriptives (hourly wages)"),
    ("t_groupspecs_hw", "Table A7 — Group-level spillover effects, revised specification (log hourly wages)"),
    ("t_horserace_hw",  "Table A8 — Group-Specific Connectivity and Firm-Level Outcomes (log hourly wages)"),
]

PREAMBLE = r"""\documentclass[11pt]{article}
\usepackage[paperwidth=8.5in,paperheight=14in,margin=0.7in]{geometry}
\usepackage{booktabs,siunitx,makecell,float,amssymb,amsmath,caption}
\usepackage[T1]{fontenc}
\captionsetup{labelformat=empty}
\pagestyle{plain}
\setlength{\parindent}{0pt}
\begin{document}

{\Large\bfseries Within-firm exhibits --- Tables A6, A7 and A8\par}
\vspace{6pt}

Generated by \texttt{run\_all.R} from the Stata inputs in \texttt{data/}. The
LaTeX is produced by \texttt{05b\_make\_tables\_within\_firm.py}, unmodified.

\textit{Table A7 revision.} Three controls are added to the two group-level
columns; nothing is removed. See \texttt{SPEC.md} for the exact fixed-effect
lists.
\begin{enumerate}\itemsep1pt
\item The year interactions are allowed to differ by worker group:
      group $\times$ industry $\times$ year, group $\times$ microregion
      $\times$ year, group $\times$ negotiation-month $\times$ year. The plain
      versions are then omitted, being nested inside these.
\item The three pre-treatment quartile bins are made group-specific. They are
      already computed per establishment $\times$ group; only their year path
      was shared.
\item The ``Overall'' column gains the firm-level pre-treatment wage,
      employment and flow bins $\times$ year, the same ones Table A7 column~(1)
      uses. ``Within firms'' absorbs them through establishment $\times$ year.
\end{enumerate}

\textit{Unchanged.} Table A6, the firm-level columns of Table A7, and Table A8
are firm-level objects and are not affected.

\vspace{4pt}\hrule
\clearpage
"""


def main() -> int:
    work = ROOT / "output" / "_tex"
    if work.exists():
        shutil.rmtree(work)
    work.mkdir(parents=True)

    body = []
    for stem, heading in TABLES:
        src = OUTPUT / f"{stem}.tex"
        if not src.exists():
            sys.exit(f"missing {src} -- run 05b_make_tables_within_firm.py first")
        body.append(r"\section*{" + heading + "}")
        body.append(src.read_text())
        body.append(r"\clearpage")

    tex = work / "tables.tex"
    tex.write_text(PREAMBLE + "\n".join(body) + "\n\\end{document}\n")
    for _ in range(2):
        proc = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex.name],
            cwd=work, capture_output=True, text=True)
    pdf = work / "tables.pdf"
    if not pdf.exists():
        print("pdflatex failed:", file=sys.stderr)
        for line in proc.stdout.splitlines():
            if line.startswith("!"):
                print("   ", line, file=sys.stderr)
        return 1
    dest = ROOT / "tables_A6_A7_A8.pdf"
    shutil.copy(pdf, dest)
    print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
