********************************************************************************
* cba_dotprod_decomposition.do
*
* Bilinear A/B/C/cross decomposition with pretrend-aware reference.
*
* For each (untreated focal i, cba_period t):
*   Anchors (firm-specific, FE-absorbed):
*     u_bar_i = mean(u_{i, t in {1,2}})
*     T_bar_i = mean(T_{i, t in {1,2}})
*
*   Raw outcomes (counts):
*     dot_raw_A     = u_t  . T_t
*     dot_raw_B     = u_bar . T_t                 (focal anchored at pre-avg)
*     dot_raw_C     = u_t  . T_bar                (partner anchored at pre-avg)
*     dot_raw_cross = (u_t - u_bar) . (T_t - T_bar)
*
*   Shares outcomes (clause-share simplex vectors): analogous.
*
* By bilinearity of u . T and linearity of OLS in the outcome, with
* establishment fixed effects absorbing the firm-specific anchor term
* (u_bar . T_bar), the regression identity
*       beta_A = beta_B + beta_C + beta_cross
* holds exactly (machine precision). The LaTeX generator verifies this.
*
* Same uncorrected `bilateral_conn_pw` weights as Exercises A/B/C; same
* sample (lagos_sample_avg==1 & treat_ultra==0 & in_balanced_panel==1);
* same FE structure; only the OUTCOME changes.
*
* Pipeline:
*   1. Load + setup variables (mirrors cba_similarity.do)
*   2. Export clause data for Python prep (already done by upstream pipeline,
*      so we only re-export if the file is missing)
*   3. Python computes the 8 bilinear outcomes (cba_dotprod_decomposition_prep.py)
*   4. Merge bilinear panel and run regressions
*
* Outputs:
*   Tables/cba_similarity/results_spill_dotprod_raw.csv
*   Tables/cba_similarity/results_spill_dotprod_shares.csv
*   (LaTeX tables generated by generate_dotprod_decomposition_latex.py)
*
* NOTE: For the `_cross` outcomes, pre-trend regression is mechanically
*       degenerate. cross at period 1 equals cross at period 2 by construction
*       (the anchor is symmetric: u_bar = (u_1 + u_2)/2 implies u_1 - u_bar =
*       -(u_2 - u_bar)), so the within-firm pre-period variation in cross is
*       zero and firm FE fully absorbs it. We report the pre coefficient as 0
*       with NA p-value for cross outcomes.
********************************************************************************

capture log close
local d = subinstr("`c(current_date)'"," ","_",.)
local t = subinstr("`c(current_time)'",":","",.)
cap mkdir "$logs/cba_similarity"
log using "$logs/cba_similarity/cba_dotprod_decomposition_`d'_`t'.log", replace text

di "Started: `c(current_date)' `c(current_time)'"
di "Stata version: `c(stata_version)'"

cap mkdir "$tables/cba_similarity"

********************************************************************************
* SECTION 1: LOAD DATA + MERGE TOTALFLOWS
********************************************************************************

use "$rais_firm/lagos_sample_sep24_pct_unionexp_ext_df2.dta", clear

preserve
	import delimited "$rais_aux/totalflows_wide_2007_2011.csv", clear
	tostring identificad, replace format(%014.0f) force
	tempfile totalflows_wide
	save `totalflows_wide'
restore

merge m:1 identificad using `totalflows_wide', keep(master match) nogen

gen double totalflows_pw_pre_07_11 = 0
gen        totalflows_pw_pre_07_11_cnt = 0
foreach yp in totalflows_pw_07_08 totalflows_pw_08_09 totalflows_pw_09_10 totalflows_pw_10_11 {
	replace totalflows_pw_pre_07_11     = totalflows_pw_pre_07_11 + `yp' if !missing(`yp')
	replace totalflows_pw_pre_07_11_cnt = totalflows_pw_pre_07_11_cnt + (!missing(`yp'))
}
replace totalflows_pw_pre_07_11 = totalflows_pw_pre_07_11 / totalflows_pw_pre_07_11_cnt ///
	if totalflows_pw_pre_07_11_cnt > 0
replace totalflows_pw_pre_07_11 = . if totalflows_pw_pre_07_11_cnt == 0
drop totalflows_pw_pre_07_11_cnt

keep if year >= 2009
keep if lagos_sample_avg == 1

di as result "Sample size after restrictions: " _N

********************************************************************************
* SECTION 2: VARIABLE CREATION (mirrors cba_similarity.do)
********************************************************************************

cap drop cba_period
cap drop pre_treat_cba
cap drop post_treat_cba

gen cba_period = .
replace cba_period = 1 if avg_file_date == earliest2009_avg - 1 & !missing(avg_file_date)
replace cba_period = 2 if avg_file_date == second_cba_avg & !missing(avg_file_date)
replace cba_period = 3 if inrange(avg_file_date, mdy(1,1,2013), mdy(12,31,2013)) & cba_period == .
replace cba_period = 4 if inrange(avg_file_date, mdy(1,1,2014), mdy(12,31,2014)) & cba_period == .
replace cba_period = 5 if inrange(avg_file_date, mdy(1,1,2015), mdy(12,31,2015)) & cba_period == .
replace cba_period = 6 if inrange(avg_file_date, mdy(1,1,2016), mdy(12,31,2016)) & cba_period == .
label var cba_period "CBA negotiation period"

gen pre_treat_cba  = cond(cba_period < 2,  1, 0)
gen post_treat_cba = cond(cba_period >= 3, 1, 0) if !missing(cba_period)

local s_spill "lagos_sample_avg==1 & treat_ultra==0 & in_balanced_panel==1"

cap drop totaltreat_pw_n_p90
cap drop totaltreat_pw_norm
sum totaltreat_pw_n if `s_spill' & year == 2009, detail
gen totaltreat_pw_n_p90 = r(p90)
label var totaltreat_pw_n_p90 "90th pctile of total flows to treated (spillover sample, 2009)"
gen totaltreat_pw_norm = totaltreat_pw_n / totaltreat_pw_n_p90
label var totaltreat_pw_norm "Connectivity scaled to 90th pctile"

cap drop firm_emp_pre_o
cap drop firm_emp_pre
quietly {
	bys identificad: egen firm_emp_pre_o = mean(firm_emp) if inrange(year, 2009, 2011)
	bys identificad: egen firm_emp_pre = min(firm_emp_pre_o)
	drop firm_emp_pre_o
}
cap drop l_firm_emp_pre
gen double l_firm_emp_pre = ln(firm_emp_pre)
label var l_firm_emp_pre "Log pre-treatment firm employment"

cap drop l_firm_emp_pre4_o
cap drop l_firm_emp_pre4
quietly {
	egen l_firm_emp_pre4_o = cut(l_firm_emp_pre) if year == 2009 & in_balanced_panel == 1, group(4)
	bys identificad: egen l_firm_emp_pre4 = min(l_firm_emp_pre4_o)
	drop l_firm_emp_pre4_o
}

cap drop totalflows_pw_pre_07_114_o
cap drop totalflows_pw_pre_07_114
quietly {
	egen totalflows_pw_pre_07_114_o = cut(totalflows_pw_pre_07_11) ///
		if year == 2009 & in_balanced_panel == 1, group(4)
	bys identificad: egen totalflows_pw_pre_07_114 = min(totalflows_pw_pre_07_114_o)
	drop totalflows_pw_pre_07_114_o
	replace totalflows_pw_pre_07_114 = 0 if missing(totalflows_pw_pre_07_114)
}

********************************************************************************
* SECTION 3: EXPORT CLAUSE DATA + RUN PYTHON PREP IF NEEDED
* (idempotent — if the bilinear panel already exists from an earlier run,
*  we skip these steps to save time)
********************************************************************************

cap confirm file "$rais_aux/cba_dotprod_decomposition_panel.dta"
if _rc != 0 {
	di as result "Bilinear panel not found; re-running clause export + Python prep."

	cap confirm file "$rais_aux/cba_clauses_by_period.dta"
	if _rc != 0 {
		ds cl_*
		local clause_vars `r(varlist)'
		preserve
			keep if !missing(cba_period)
			keep identificad cba_period treat_ultra lagos_sample_avg in_balanced_panel `clause_vars'
			foreach v of local clause_vars {
				replace `v' = 0 if missing(`v')
			}
			save "$rais_aux/cba_clauses_by_period.dta", replace
		restore
	}

	shell ~/.conda/envs/venv_python312/bin/python "$programs/cba_similarity/cba_dotprod_decomposition_prep.py"
}
else {
	di as result "Bilinear panel exists; skipping clause export + Python prep."
}

********************************************************************************
* SECTION 4: MERGE BILINEAR PANEL
********************************************************************************

di as result "Merging bilinear decomposition outcomes into panel..."

merge m:1 identificad cba_period using "$rais_aux/cba_dotprod_decomposition_panel.dta", ///
	keep(master match) gen(m_dot)
drop m_dot

local raw_outcomes    "dot_raw_A dot_raw_B dot_raw_C dot_raw_cross"
local shares_outcomes "dot_shares_A dot_shares_B dot_shares_C dot_shares_cross"
local cos_outcomes    "cos_A cos_B cos_C"
local ruz_outcomes    "ruz_A ruz_B ruz_C"
local all_outcomes "`raw_outcomes' `shares_outcomes' `cos_outcomes' `ruz_outcomes'"

label var dot_raw_A        "u_t . T_t (raw counts)"
label var dot_raw_B        "u_bar . T_t (raw counts)"
label var dot_raw_C        "u_t . T_bar (raw counts)"
label var dot_raw_cross    "(u_t - u_bar) . (T_t - T_bar) (raw counts)"
label var dot_shares_A     "s_u_t . s_T_t (shares)"
label var dot_shares_B     "s_u_bar . s_T_t (shares)"
label var dot_shares_C     "s_u_t . s_T_bar (shares)"
label var dot_shares_cross "(s_u_t - s_u_bar) . (s_T_t - s_T_bar) (shares)"
label var cos_A           "Cosine: cos(u_t, T_t)"
label var cos_B           "Cosine: cos(u_bar, T_t)"
label var cos_C           "Cosine: cos(u_t, T_bar)"
label var ruz_A           "Ruzicka: ruz(u_t, T_t)"
label var ruz_B           "Ruzicka: ruz(u_bar, T_t)"
label var ruz_C           "Ruzicka: ruz(u_t, T_bar)"

di as result "Bilinear merge complete. Observations with each outcome:"
foreach v of local all_outcomes {
	count if !missing(`v')
	di as text "  `v': " r(N)
}

********************************************************************************
* SECTION 5: PRE-TREATMENT QUARTILE BINS FOR EACH OUTCOME
********************************************************************************

foreach v of local all_outcomes {
	cap drop `v'_pre_o
	cap drop `v'_pre
	quietly {
		bys identificad: egen `v'_pre_o = mean(`v') if inrange(cba_period, 1, 2)
		bys identificad: egen `v'_pre = min(`v'_pre_o)
		drop `v'_pre_o
	}

	cap drop `v'_pre4_o
	cap drop `v'_pre4
	quietly {
		egen `v'_pre4_o = cut(`v'_pre) if year == 2009 & in_balanced_panel == 1, group(4)
		bys identificad: egen `v'_pre4 = min(`v'_pre4_o)
		drop `v'_pre4_o
		replace `v'_pre4 = 0 if missing(`v'_pre4)
	}
}

********************************************************************************
* SECTION 6: SPECIFICATION MACROS
********************************************************************************

local conn              "totaltreat_pw_norm"
local base_fe_cba       "identificad i.industry1#i.cba_period i.mode_base_month#i.cba_period i.microregion#i.cba_period"
local base_fe_cba_union "identificad i.industry1#i.cba_period i.mode_base_month#i.cba_period i.microregion#i.cba_period i.mode_union#i.cba_period"
local extra_cba         "ib0.totalflows_pw_pre_07_114#i.cba_period"

********************************************************************************
* SECTION 7: INITIALIZE OUTPUT CSV FILES
********************************************************************************

capture erase "$tables/cba_similarity/results_spill_dotprod_raw.csv"
tempname fh
file open `fh' using "$tables/cba_similarity/results_spill_dotprod_raw.csv", write replace
file write `fh' "spec;section;outcome;row_type;value" _n
file close `fh'

capture erase "$tables/cba_similarity/results_spill_dotprod_shares.csv"
tempname fh
file open `fh' using "$tables/cba_similarity/results_spill_dotprod_shares.csv", write replace
file write `fh' "spec;section;outcome;row_type;value" _n
file close `fh'

capture erase "$tables/cba_similarity/results_spill_cosine_pretrend_anchored.csv"
tempname fh
file open `fh' using "$tables/cba_similarity/results_spill_cosine_pretrend_anchored.csv", write replace
file write `fh' "spec;section;outcome;row_type;value" _n
file close `fh'

capture erase "$tables/cba_similarity/results_spill_ruzicka_pretrend_anchored.csv"
tempname fh
file open `fh' using "$tables/cba_similarity/results_spill_ruzicka_pretrend_anchored.csv", write replace
file write `fh' "spec;section;outcome;row_type;value" _n
file close `fh'

* Event-study CSV: one row per (spec, outcome, period in {1,3,4,5,6})
capture erase "$tables/cba_similarity/results_event_study_decomposition.csv"
tempname fh
file open `fh' using "$tables/cba_similarity/results_event_study_decomposition.csv", write replace
file write `fh' "spec;outcome;period;beta;se" _n
file close `fh'

local csv_es "$tables/cba_similarity/results_event_study_decomposition.csv"

********************************************************************************
* SECTION 8: REGRESSIONS
*   For each version v in {raw, shares}:
*     For each FE variant in {base, union}:
*       For each outcome in {A, B, C, cross}:
*         - Main regression: c.conn ## post_treat_cba
*         - Pre regression : c.conn ## pre_treat_cba on cba_period <= 2
*         - Event study   : c.conn ## ib2.cba_period, testparm pre
*         - Write rows to CSV
*
*   For `_cross` outcomes, the pre-regression's coefficient is mechanically
*   zero (within-firm constant across periods 1,2). We trap the regression in
*   `capture` and write 0 with NA p-value if it fails.
********************************************************************************

local spec_raw    "dotprod_raw"
local spec_shares "dotprod_shares"

foreach version in raw shares {

	local csv_path  "$tables/cba_similarity/results_spill_dotprod_`version'.csv"
	local outcomes  "`version'_outcomes_local"
	if "`version'" == "raw"    local cur_outcomes "`raw_outcomes'"
	if "`version'" == "shares" local cur_outcomes "`shares_outcomes'"
	local cur_spec_base "spec_`version'"

	di _newline(2)
	di as result "-----------------------------------------------------------------------"
	di as result "BILINEAR DECOMPOSITION — version: `version'"
	di as result "-----------------------------------------------------------------------"

	foreach fe_variant in base union {
		if "`fe_variant'" == "base" {
			local cur_base_fe "`base_fe_cba'"
			local cur_spec    "dotprod_`version'"
		}
		else {
			local cur_base_fe "`base_fe_cba_union'"
			local cur_spec    "dotprod_`version'_union"
		}

		* Common pre4 control across A/B/C/cross within a version, so that
		* identical RHS produces the exact regression identity
		*   beta_A = beta_B + beta_C + beta_cross
		* Use the A-outcome's pre4 (headline "both moving" pre-treatment level)
		* uniformly. Outcome-specific pre4 controls would break linearity across
		* the four regressions.
		local common_pre4 "dot_`version'_A_pre4"

		foreach outcome of local cur_outcomes {

			di as text "  Estimating: `outcome' (`fe_variant')"

			local absorb_cba "`cur_base_fe' ib0.`common_pre4'#i.cba_period ib0.l_firm_emp_pre4#i.cba_period `extra_cba'"

			* Main regression
			reghdfe `outcome' c.`conn'##post_treat_cba ///
				if `s_spill' & !missing(cba_period) & !missing(`outcome'), ///
				absorb(`absorb_cba') vce(cluster identificad)

			local b_post  = _b[1.post_treat_cba#c.`conn']
			local se_post = _se[1.post_treat_cba#c.`conn']
			local p_post  = 2*ttail(e(df_r), abs(`b_post'/`se_post'))
			local n_obs   = e(N)
			local n_estab = e(N_clust)

			qui sum `outcome' if e(sample) & cba_period == 2
			local base_mean = cond(r(N) > 0, r(mean), .)

			* Pre regression — trap degeneracy for cross outcomes
			local cross_outcome = (strpos("`outcome'", "_cross") > 0)
			local b_pre  = 0
			local se_pre = 0
			local p_pre  = .

			if !`cross_outcome' {
				capture noisily reghdfe `outcome' c.`conn'##pre_treat_cba ///
					if `s_spill' & !missing(cba_period) & cba_period <= 2 & !missing(`outcome'), ///
					absorb(`absorb_cba') vce(cluster identificad)
				if _rc == 0 {
					local b_pre  = _b[1.pre_treat_cba#c.`conn']
					local se_pre = _se[1.pre_treat_cba#c.`conn']
					if `se_pre' > 0 {
						local p_pre = 2*ttail(e(df_r), abs(`b_pre'/`se_pre'))
					}
				}
			}

			* Event study + pre-trend F-test
			capture noisily reghdfe `outcome' c.`conn'##ib2.cba_period ///
				if `s_spill' & !missing(cba_period) & !missing(`outcome'), ///
				absorb(`absorb_cba') vce(cluster identificad)
			if _rc == 0 {
				capture testparm c.`conn'#1.cba_period
				local pre_ftest_pval = cond(_rc == 0, r(p), .)

				* Extract period-specific betas from event study
				foreach p in 1 3 4 5 6 {
					capture local b_es  = _b[`p'.cba_period#c.`conn']
					capture local se_es = _se[`p'.cba_period#c.`conn']
					if "`b_es'" != "" & "`se_es'" != "" {
						tempname fh
						file open `fh' using "`csv_es'", write append
						file write `fh' `""`cur_spec'";"`outcome'";"`p'";"' %15.6f (`b_es') ";" %15.6f (`se_es') _n
						file close `fh'
					}
				}
			}
			else {
				local pre_ftest_pval = .
			}

			local stars_post ""
			if `p_post' < 0.01                          local stars_post "***"
			else if (`p_post' < 0.05 & `p_post' > 0.01) local stars_post "**"
			else if (`p_post' < 0.10 & `p_post' > 0.05) local stars_post "*"

			local stars_pre ""
			if !missing(`p_pre') {
				if `p_pre' < 0.01                          local stars_pre "***"
				else if (`p_pre' < 0.05 & `p_pre' > 0.01) local stars_pre "**"
				else if (`p_pre' < 0.10 & `p_pre' > 0.05) local stars_pre "*"
			}

			tempname fh
			file open `fh' using "`csv_path'", write append
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"main";"'   %15.6f (`b_post')  `"`stars_post'"' _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"main_se";"' %15.6f (`se_post') _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre";"'    %15.6f (`b_pre')  `"`stars_pre'"' _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre_se";"'  %15.6f (`se_pre') _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"baseline_mean";"' %15.6f (`base_mean') _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"n_obs";"'   %12.0fc (`n_obs') _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"n_estab";"' %12.0fc (`n_estab') _n
			file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre_pval";"' %9.4f (`pre_ftest_pval') _n
			file close `fh'
		}
	}
}

di as result _newline "All bilinear regressions complete."

********************************************************************************
* SECTION 8b: COSINE WITH PRETREND-CORRECTED ANCHORS
*   No bilinear identity (cosine is non-linear) — three independent regressions:
*     cos_A: cos(u_t, T_t)        — both moving (= Exercise A from cosine table)
*     cos_B: cos(u_bar, T_t)      — focal anchored at pre-avg (vs period-2 in
*                                   the original focal_frozen exercise)
*     cos_C: cos(u_t, T_bar)      — partners anchored at pre-avg
*   Uses cos_A's pre4 as common control for cleanest comparison to the bilinear
*   block above; standard errors and significance are NOT additive across the
*   three cosine columns.
********************************************************************************

di _newline(2)
di as result "-----------------------------------------------------------------------"
di as result "COSINE — pretrend-anchored A/B/C (no identity)"
di as result "-----------------------------------------------------------------------"

local csv_cos "$tables/cba_similarity/results_spill_cosine_pretrend_anchored.csv"

foreach fe_variant in base union {
	if "`fe_variant'" == "base" {
		local cur_base_fe "`base_fe_cba'"
		local cur_spec    "cosine_pretrend_anchored"
	}
	else {
		local cur_base_fe "`base_fe_cba_union'"
		local cur_spec    "cosine_pretrend_anchored_union"
	}

	local common_pre4 "cos_A_pre4"

	foreach outcome of local cos_outcomes {

		di as text "  Estimating: `outcome' (`fe_variant')"

		local absorb_cba "`cur_base_fe' ib0.`common_pre4'#i.cba_period ib0.l_firm_emp_pre4#i.cba_period `extra_cba'"

		reghdfe `outcome' c.`conn'##post_treat_cba ///
			if `s_spill' & !missing(cba_period) & !missing(`outcome'), ///
			absorb(`absorb_cba') vce(cluster identificad)

		local b_post  = _b[1.post_treat_cba#c.`conn']
		local se_post = _se[1.post_treat_cba#c.`conn']
		local p_post  = 2*ttail(e(df_r), abs(`b_post'/`se_post'))
		local n_obs   = e(N)
		local n_estab = e(N_clust)

		qui sum `outcome' if e(sample) & cba_period == 2
		local base_mean = cond(r(N) > 0, r(mean), .)

		reghdfe `outcome' c.`conn'##pre_treat_cba ///
			if `s_spill' & !missing(cba_period) & cba_period <= 2 & !missing(`outcome'), ///
			absorb(`absorb_cba') vce(cluster identificad)

		local b_pre  = _b[1.pre_treat_cba#c.`conn']
		local se_pre = _se[1.pre_treat_cba#c.`conn']
		local p_pre  = 2*ttail(e(df_r), abs(`b_pre'/`se_pre'))

		capture noisily reghdfe `outcome' c.`conn'##ib2.cba_period ///
			if `s_spill' & !missing(cba_period) & !missing(`outcome'), ///
			absorb(`absorb_cba') vce(cluster identificad)
		if _rc == 0 {
			capture testparm c.`conn'#1.cba_period
			local pre_ftest_pval = cond(_rc == 0, r(p), .)

			* Extract period-specific betas from event study
			foreach p in 1 3 4 5 6 {
				capture local b_es  = _b[`p'.cba_period#c.`conn']
				capture local se_es = _se[`p'.cba_period#c.`conn']
				if "`b_es'" != "" & "`se_es'" != "" {
					tempname fh
					file open `fh' using "`csv_es'", write append
					file write `fh' `""`cur_spec'";"`outcome'";"`p'";"' %15.6f (`b_es') ";" %15.6f (`se_es') _n
					file close `fh'
				}
			}
		}
		else {
			local pre_ftest_pval = .
		}

		local stars_post ""
		if `p_post' < 0.01                          local stars_post "***"
		else if (`p_post' < 0.05 & `p_post' > 0.01) local stars_post "**"
		else if (`p_post' < 0.10 & `p_post' > 0.05) local stars_post "*"

		local stars_pre ""
		if !missing(`p_pre') {
			if `p_pre' < 0.01                          local stars_pre "***"
			else if (`p_pre' < 0.05 & `p_pre' > 0.01) local stars_pre "**"
			else if (`p_pre' < 0.10 & `p_pre' > 0.05) local stars_pre "*"
		}

		tempname fh
		file open `fh' using "`csv_cos'", write append
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"main";"'   %15.6f (`b_post')  `"`stars_post'"' _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"main_se";"' %15.6f (`se_post') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre";"'    %15.6f (`b_pre')  `"`stars_pre'"' _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre_se";"'  %15.6f (`se_pre') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"baseline_mean";"' %15.6f (`base_mean') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"n_obs";"'   %12.0fc (`n_obs') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"n_estab";"' %12.0fc (`n_estab') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre_pval";"' %9.4f (`pre_ftest_pval') _n
		file close `fh'
	}
}

di as result _newline "All cosine regressions complete."

********************************************************************************
* SECTION 8c: RUZICKA (WEIGHTED JACCARD) WITH PRETREND-CORRECTED ANCHORS
*   Magnitude-sensitive complement to cosine: stricter than Bray-Curtis (uses
*   max in denominator), so a size mismatch between u and T penalizes
*   similarity even when angle is identical. Non-linear (no bilinear identity).
********************************************************************************

di _newline(2)
di as result "-----------------------------------------------------------------------"
di as result "RUZICKA — pretrend-anchored A/B/C (magnitude-sensitive, no identity)"
di as result "-----------------------------------------------------------------------"

local csv_ruz "$tables/cba_similarity/results_spill_ruzicka_pretrend_anchored.csv"

foreach fe_variant in base union {
	if "`fe_variant'" == "base" {
		local cur_base_fe "`base_fe_cba'"
		local cur_spec    "ruzicka_pretrend_anchored"
	}
	else {
		local cur_base_fe "`base_fe_cba_union'"
		local cur_spec    "ruzicka_pretrend_anchored_union"
	}

	local common_pre4 "ruz_A_pre4"

	foreach outcome of local ruz_outcomes {

		di as text "  Estimating: `outcome' (`fe_variant')"

		local absorb_cba "`cur_base_fe' ib0.`common_pre4'#i.cba_period ib0.l_firm_emp_pre4#i.cba_period `extra_cba'"

		reghdfe `outcome' c.`conn'##post_treat_cba ///
			if `s_spill' & !missing(cba_period) & !missing(`outcome'), ///
			absorb(`absorb_cba') vce(cluster identificad)

		local b_post  = _b[1.post_treat_cba#c.`conn']
		local se_post = _se[1.post_treat_cba#c.`conn']
		local p_post  = 2*ttail(e(df_r), abs(`b_post'/`se_post'))
		local n_obs   = e(N)
		local n_estab = e(N_clust)

		qui sum `outcome' if e(sample) & cba_period == 2
		local base_mean = cond(r(N) > 0, r(mean), .)

		reghdfe `outcome' c.`conn'##pre_treat_cba ///
			if `s_spill' & !missing(cba_period) & cba_period <= 2 & !missing(`outcome'), ///
			absorb(`absorb_cba') vce(cluster identificad)

		local b_pre  = _b[1.pre_treat_cba#c.`conn']
		local se_pre = _se[1.pre_treat_cba#c.`conn']
		local p_pre  = 2*ttail(e(df_r), abs(`b_pre'/`se_pre'))

		capture noisily reghdfe `outcome' c.`conn'##ib2.cba_period ///
			if `s_spill' & !missing(cba_period) & !missing(`outcome'), ///
			absorb(`absorb_cba') vce(cluster identificad)
		if _rc == 0 {
			capture testparm c.`conn'#1.cba_period
			local pre_ftest_pval = cond(_rc == 0, r(p), .)

			* Extract period-specific betas from event study
			foreach p in 1 3 4 5 6 {
				capture local b_es  = _b[`p'.cba_period#c.`conn']
				capture local se_es = _se[`p'.cba_period#c.`conn']
				if "`b_es'" != "" & "`se_es'" != "" {
					tempname fh
					file open `fh' using "`csv_es'", write append
					file write `fh' `""`cur_spec'";"`outcome'";"`p'";"' %15.6f (`b_es') ";" %15.6f (`se_es') _n
					file close `fh'
				}
			}
		}
		else {
			local pre_ftest_pval = .
		}

		local stars_post ""
		if `p_post' < 0.01                          local stars_post "***"
		else if (`p_post' < 0.05 & `p_post' > 0.01) local stars_post "**"
		else if (`p_post' < 0.10 & `p_post' > 0.05) local stars_post "*"

		local stars_pre ""
		if !missing(`p_pre') {
			if `p_pre' < 0.01                          local stars_pre "***"
			else if (`p_pre' < 0.05 & `p_pre' > 0.01) local stars_pre "**"
			else if (`p_pre' < 0.10 & `p_pre' > 0.05) local stars_pre "*"
		}

		tempname fh
		file open `fh' using "`csv_ruz'", write append
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"main";"'   %15.6f (`b_post')  `"`stars_post'"' _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"main_se";"' %15.6f (`se_post') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre";"'    %15.6f (`b_pre')  `"`stars_pre'"' _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre_se";"'  %15.6f (`se_pre') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"baseline_mean";"' %15.6f (`base_mean') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"n_obs";"'   %12.0fc (`n_obs') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"n_estab";"' %12.0fc (`n_estab') _n
		file write `fh' `""`cur_spec'";"spill";"`outcome'";"pre_pval";"' %9.4f (`pre_ftest_pval') _n
		file close `fh'
	}
}

di as result _newline "All Ruzicka regressions complete."

********************************************************************************
* SECTION 9: COMPLETION + AUTO-RUN PYTHON FOR LATEX TABLE
********************************************************************************

log close
di as result "Finished: `c(current_date)' `c(current_time)'"

shell ~/.conda/envs/venv_python312/bin/python "$programs/cba_similarity/generate_dotprod_decomposition_latex.py"
di as result "LaTeX tables written to Tables/cba_similarity/dotprod_*_decomposition_table.tex"

shell source "$programs/notify.sh" && notify "cba_dotprod_decomposition done" "Bilinear decomposition regressions and tables complete"

********************************************************************************
* END
********************************************************************************
