%% Clear Workspace
clear; clc; close all;

%% Define the available years
start_year = 2007;
end_year   = 2011;

%% Load unbalanced treatment indicator
% Generated by Programs/entry_exit/041_merge_cba_rais_unbal.do
% Firms with CBA requirement fulfilled AND treat_ultra==1, NO pos_emp restriction
treat_unbal = readtable("/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/entry_exit_treat.csv");
treat_unbal.identificad = string(treat_unbal.identificad);

%% Initialize cell to store connectivity measures per year-pair
conntables = {};

%% Loop: compute connectivity matrix for every two consecutive years
for y = start_year:(end_year-1)
    next_y = (y+1);

    filename = sprintf('/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/employers_%d_%d.csv', y, next_y);
    employers = readtable(filename);

    estab_y    = string(employers.(['identificad_' num2str(y)]));
    estab_next = string(employers.(['identificad_' num2str(next_y)]));

    unique_estabs = unique([estab_y; estab_next]);
    n_estabs = length(unique_estabs);

    [~, estab_y_idx]    = ismember(estab_y,    unique_estabs);
    [~, estab_next_idx] = ismember(estab_next, unique_estabs);

    valid_idx      = (estab_y_idx > 0) & (estab_next_idx > 0);
    estab_y_idx    = estab_y_idx(valid_idx);
    estab_next_idx = estab_next_idx(valid_idx);

    % Load and map employment
    emp_y    = employers.(['firm_emp_' num2str(y)]);
    emp_next = employers.(['firm_emp_' num2str(next_y)]);

    emp_y_mapped    = zeros(n_estabs, 1);
    emp_next_mapped = zeros(n_estabs, 1);

    [found_y,    idx_y]    = ismember(estab_y,    unique_estabs);
    [found_next, idx_next] = ismember(estab_next, unique_estabs);

    emp_y_mapped(idx_y(found_y))       = emp_y(found_y);
    emp_next_mapped(idx_next(found_next)) = emp_next(found_next);

    avg_emp = (emp_y_mapped + emp_next_mapped) / 2;
    avg_emp(avg_emp == 0) = NaN;

    % Adjacency matrix (zero diagonal)
    M_estabs = sparse(estab_y_idx, estab_next_idx, 1, n_estabs, n_estabs);
    M_estabs(1:n_estabs+1:end) = 0;

    % Mark unbalanced treated establishments
    [~, treat_idx] = ismember(unique_estabs, treat_unbal.identificad);
    is_treat = zeros(n_estabs, 1);
    is_treat(treat_idx > 0) = treat_unbal.lagos_treat_unbal(treat_idx(treat_idx > 0));

    % Total flows
    totalOut   = full(sum(M_estabs, 2));
    totalIn    = full(sum(M_estabs, 1))';
    totalFlows = totalOut + totalIn;

    % Flows to/from unbalanced treated firms
    outToTreat   = full(sum(M_estabs(:, is_treat == 1), 2));
    inFromTreat  = full(sum(M_estabs(is_treat == 1, :), 1))';
    TreatFlows   = outToTreat + inFromTreat;

    % Normalize by average employment
    norm_totalOut    = totalOut    ./ avg_emp;
    norm_totalIn     = totalIn     ./ avg_emp;
    norm_totalFlows  = totalFlows  ./ avg_emp;
    norm_outToTreat  = outToTreat  ./ avg_emp;
    norm_inFromTreat = inFromTreat ./ avg_emp;
    norm_TreatFlows  = TreatFlows  ./ avg_emp;

    T_pair = table(unique_estabs, ...
        totalOut, totalIn, totalFlows, ...
        norm_totalOut, norm_totalIn, norm_totalFlows, ...
        outToTreat, inFromTreat, TreatFlows, ...
        norm_outToTreat, norm_inFromTreat, norm_TreatFlows, ...
        'VariableNames', { ...
            'identificad1', ...
            'total_out','total_in','total_flows', ...
            'total_out_pw','total_in_pw','total_flows_pw', ...
            'out_treat','in_treat','treat_flows', ...
            'out_treat_pw','in_treat_pw','treat_flows_pw' ...
        });

    T_pair.Properties.VariableNames{'total_out'}    = sprintf('totalout_%d_%d',    y, next_y);
    T_pair.Properties.VariableNames{'total_in'}     = sprintf('totalin_%d_%d',     y, next_y);
    T_pair.Properties.VariableNames{'total_flows'}  = sprintf('totalflows_%d_%d',  y, next_y);
    T_pair.Properties.VariableNames{'out_treat'}    = sprintf('outtreat_%d_%d',    y, next_y);
    T_pair.Properties.VariableNames{'in_treat'}     = sprintf('intreat_%d_%d',     y, next_y);
    T_pair.Properties.VariableNames{'treat_flows'}  = sprintf('totaltreat_%d_%d',  y, next_y);

    T_pair.Properties.VariableNames{'total_out_pw'}   = sprintf('totalout_pw_%d_%d',   y, next_y);
    T_pair.Properties.VariableNames{'total_in_pw'}    = sprintf('totalin_pw_%d_%d',    y, next_y);
    T_pair.Properties.VariableNames{'total_flows_pw'} = sprintf('totalflows_pw_%d_%d', y, next_y);
    T_pair.Properties.VariableNames{'out_treat_pw'}   = sprintf('outtreat_pw_%d_%d',   y, next_y);
    T_pair.Properties.VariableNames{'in_treat_pw'}    = sprintf('intreat_pw_%d_%d',    y, next_y);
    T_pair.Properties.VariableNames{'treat_flows_pw'} = sprintf('totaltreat_pw_%d_%d', y, next_y);

    conntables{end+1} = T_pair;

    fprintf('Processed connectivity (treat unbal) for year pair %d-%d.\n', y, next_y);
end

%% Merge all year-pair tables
finaltable = conntables{1};
for k = 2:length(conntables)
    finaltable = outerjoin(finaltable, conntables{k}, 'MergeKeys', true, 'Type', 'full');
end

finaltable = sortrows(finaltable, 'identificad1');

outputFile = '/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/connectivity_treat_unbal_2007_2011.csv';
writetable(finaltable, outputFile);
fprintf('Saved: %s\n', outputFile);
