#!/usr/bin/env python3
"""Build the six within-firm exhibits (A6/A7/A8, monthly + hourly) into one PDF.

    ~/.conda/envs/venv_python312/bin/python 04_build_pdf.py

Reads the canonical CSVs written by _run_within_firm_v2.do and
_run_within_firm_hw_v2.do, generates the LaTeX fragments with the table
generator from the within_firm_final package, and compiles them with that
package's preamble so the layout matches tables_A6_A7_A8.pdf exactly.

Requires texlive on PATH:  module load texlive/2026
"""
from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path("/kellogg/proj/lgg3230/UnionSpill")
TABLE_DIR = ROOT / "Tables/layer_connectivity/07_within_firm"
PKG = ROOT / "Programs/within_firm_final/scripts"
MAKE_TABLES = PKG / "05b_make_tables_within_firm.py"
BUILD_PDF = PKG / "build_pdf.py"
DEST = ROOT / "quality_reports/replication/hourly_variant_currentconn/tables_A6_A7_A8.pdf"

PROVENANCE = r"""\textbf{Stata v2 port.} Estimated by
\texttt{01b\_within\_firm\_estimates}\allowbreak\texttt{\{,\_hw\}.do} in
\texttt{07\_within\_firm/} of the canonical pipeline, from the canonical
inputs. The LaTeX is produced by
\texttt{05b\_make\_tables\_within\_firm.py}, unmodified, over the CSVs in
\texttt{Tables/layer\_connectivity/07\_within\_firm/}.
The pre-revision estimates are archived under
\texttt{archive\_oldspec\_2026-07-31/} in that same directory.

\textcolor{red}{\textbf{Caveat.} The table notes below are inherited unchanged
from \texttt{05b\_make\_tables\_within\_firm.py} and still describe the
\emph{old} fixed-effect list.} Under the revised specification the industry,
microregion and negotiation-month year interactions are group-interacted, and
the ``Overall'' column additionally carries the firm-level pre-treatment bins.
The numbers are correct; this prose is not, and must be rewritten before the
tables go into the paper."""

OLD_PROVENANCE = r"""Generated by \texttt{run\_all.R} from the Stata inputs in \texttt{data/}. The
LaTeX is produced by \texttt{05b\_make\_tables\_within\_firm.py}, unmodified."""


def load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    if not shutil.which("pdflatex"):
        sys.exit("pdflatex not on PATH -- run: module load texlive/2026")

    # 1. fragments, straight from the canonical CSVs (no staging: names match)
    subprocess.run([sys.executable, str(MAKE_TABLES), "--output-dir", str(TABLE_DIR)],
                   check=True)

    # 2. assemble with the package's own preamble and section headings
    ref = load(BUILD_PDF, "build_pdf_ref")
    preamble = ref.PREAMBLE.replace(OLD_PROVENANCE, PROVENANCE)
    if "Stata v2 port" not in preamble:
        sys.exit("preamble substitution failed -- build_pdf.py PREAMBLE changed")
    preamble = preamble.replace(r"\usepackage[T1]{fontenc}",
                                "\\usepackage[T1]{fontenc}\n\\usepackage{xcolor}")

    body = []
    for stem, heading in ref.TABLES:
        src = TABLE_DIR / f"{stem}.tex"
        if not src.exists():
            sys.exit(f"missing {src}")
        body.append(r"\section*{" + heading + "}")
        body.append(src.read_text())
        body.append(r"\clearpage")

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        tex = work / "tables.tex"
        tex.write_text(preamble + "\n".join(body) + "\n\\end{document}\n")
        for _ in range(2):
            proc = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex.name],
                cwd=work, capture_output=True, text=True)
        pdf = work / "tables.pdf"
        if not pdf.exists():
            print("pdflatex failed:", file=sys.stderr)
            for line in proc.stdout.splitlines():
                if line.startswith("!"):
                    print("   ", line, file=sys.stderr)
            return 1
        DEST.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(pdf, DEST)

    print(f"wrote {DEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
