%% Clear Workspace
clear; clc; close all;

%% Define the available years (adjust as needed)
start_year = 2009;
end_year   = 2012;

%% Load the treatment status dataset (treatment data)
% This file (treat_cnpj.csv) contains two columns:
%   - identificad: Unique employer ID (as in all your datasets)
%   - treat_ultra: Dummy variable (1 if the employer is treated, 0 otherwise)
treatData = readtable("/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/lorenzo_treat.csv");
% Convert the employer IDs to strings for consistent matching
treatData.identificad = string(treatData.identificad);

%% Initialize a cell array to store connectivity tables for each pair
connTables = {};

%% Nested loop: For each starting year y and every later year nextYear
for y = start_year:(end_year - 1)
    for nextYear = (y+1):end_year
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Read the merged data for the year pair.
        % Use sprintf to build the file name string.
        % (This file should already be generated by your Stata code.)
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        filename = sprintf('/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/employers_%d_%d.csv', y, nextYear);
        mergedData = readtable(filename);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Extract employer IDs from the merged data.
        % We assume that the variables are named "identificad_y" and "identificad_nextYear"
        % (e.g., "identificad_2009" and "identificad_2010").
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        emp_y = string(mergedData.(['identificad_' num2str(y)]));
        emp_next = string(mergedData.(['identificad_' num2str(nextYear)]));
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Build a unique employer mapping from the merged data.
        % This gives all unique employer IDs from both years.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        unique_emps = unique([emp_y; emp_next]);
        nEmps = length(unique_emps);
        
        % Map each employer ID to its index in unique_emps.
        [~, emp_y_idx] = ismember(emp_y, unique_emps);
        [~, emp_next_idx] = ismember(emp_next, unique_emps);
        
        % Remove any rows where indices are invalid (i.e., zero)
        valid_idx = (emp_y_idx > 0) & (emp_next_idx > 0);
        emp_y_idx = emp_y_idx(valid_idx);
        emp_next_idx = emp_next_idx(valid_idx);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Construct the adjacency (connectivity) matrix.
        % M(i,j) counts the number of worker flows from employer i (year y)
        % to employer j (year nextYear).
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        M = sparse(emp_y_idx, emp_next_idx, 1, nEmps, nEmps);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Assign treatment status for each unique employer.
        % For each employer in unique_emps, match it to treatData.
        % isTreated is a numeric vector where 1 = treated and 0 = untreated.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        [~, treat_idx] = ismember(unique_emps, treatData.identificad);
        isTreated = zeros(nEmps, 1);
        isTreated(treat_idx > 0) = treatData.lorenzo_treat(treat_idx(treat_idx > 0));
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Compute raw flow measures:
        % - totalOut: total workers leaving (row sum of M)
        % - totalIn: total workers arriving (column sum of M)
        % - totalFlows: sum of outflow and inflow for each employer
        % - outToTreated: outflow from employer (row sum) but only to treated firms
        % - inFromTreated: inflow into employer (column sum) but only from treated firms
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        totalOut = full(sum(M, 2));
        totalIn = full(sum(M, 1))';
        totalFlows = totalOut + totalIn;
        
        outToTreated = full(sum(M(:, isTreated == 1), 2));
        inFromTreated = full(sum(M(isTreated == 1, :), 1))';
        treatedFlows = outToTreated + inFromTreated;
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Compute connectivity percentage:
        % This is 100 * (treatedFlows / totalFlows)
        % Employers with zero total flows are assigned NaN.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        connectivityPercentage = 100 * (treatedFlows ./ totalFlows);
        connectivityPercentage(totalFlows == 0) = NaN;
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Create a table for this year pair.
        % The employer identifier is always named "identificad".
        % Other columns are the connectivity percentage, raw outflow, and raw inflow.
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        T_pair = table(unique_emps, connectivityPercentage, outToTreated, inFromTreated, ...
            'VariableNames', {'identificad', 'Connectivity_Percentage', 'OutflowTreated', 'InflowTreated'});
        
        % Rename the connectivity variables to include the year pair information.
        connVarName = sprintf('Connectivity_ltreat_%d_%d', y, nextYear);
        outVarName  = sprintf('OutflowTreated_ltreat_%d_%d', y, nextYear);
        inVarName   = sprintf('InflowTreated_ltreat_%d_%d', y, nextYear);
        
        T_pair.Properties.VariableNames{'Connectivity_Percentage'} = connVarName;
        T_pair.Properties.VariableNames{'OutflowTreated'} = outVarName;
        T_pair.Properties.VariableNames{'InflowTreated'} = inVarName;
        
        % Store this table in our cell array.
        connTables{end+1} = T_pair;
        
        fprintf('Processed connectivity measures for year pair %d-%d.\n', y, nextYear);
    end
end

%% Merge All Connectivity Tables into One Final Table
% Use an outer join on "identificad" so that every employer is included.
finalTable = connTables{1};
for k = 2:length(connTables)
    finalTable = outerjoin(finalTable, connTables{k}, 'MergeKeys', true, 'Type', 'full');
end

% (Optional) Sort the final table by identificad.
finalTable = sortrows(finalTable, 'identificad');

%% Merge the Treatment Dataset with the Final Connectivity Table
% This adds the treatment dummy (treat_ultra) to the final table.
mergedTable = outerjoin(finalTable, treatData, 'MergeKeys', true, 'Type', 'full');
% Assume missing treatment status equals 0.
missingTreat = isnan(mergedTable.lorenzo_treat);
mergedTable.lorenzo_treat(missingTreat) = 0;

%% Save the Final Merged Connectivity Dataset
outputFile = '/kellogg/proj/lgg3230/UnionSpill/Data/RAIS_aux/connectivity_ltreat_2009_2012.csv';
writetable(mergedTable, outputFile);

disp('Final merged connectivity dataset (for all pairs) with treatment dummy has been saved as connectivity_ltreat_2009_2012.csv.');